apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true" # HTTP → HTTPS 리디렉션
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - dummy.local   # 아무 도메인 넣음
      secretName: ip-tls-secret

  rules:
    - http:
        paths:
          - path: /producer
            pathType: Prefix
            backend:
              service:
                name: producer-service
                port:
                  number: 80
          - path: /consumer
            pathType: Prefix
            backend:
              service:
                name: consumer-service
                port:
                  number: 80
          - path: /order
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 80
          - path: /restaurant
            pathType: Prefix
            backend:
              service:
                name: restaurant-service
                port:
                  number: 80
          - path: /ocr
            pathType: Prefix
            backend:
              service:
                name: ocr-service
                port:
                  number: 80
