apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-deployment
  labels:
    app: ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
        - name: ocr
          image: team08registry.azurecr.io/ocr-service  # 자동으로 sha 태그 붙여서 배포됨
          ports:
            - containerPort: 8080  # Spring Boot 포트 (정적 파일 + API 모두 포함됨)
---
apiVersion: v1
kind: Service
metadata:
  name: ocr-service
spec:
  type: ClusterIP
  selector:
    app: ocr
  ports:
    - name: http
      port: 80
      targetPort: 8080
