apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-deployment
  labels:
    app: ocr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      containers:
        - name: ocr
          image: team08registry.azurecr.io/ocr-service  # 자동으로 sha 태그 붙여서 배포되니까 그대로 사용
          ports:
            - containerPort: 8080  # QR 페이지
            - containerPort: 3000  # OCR 프록시
            - containerPort: 3002  # 🔥 인증 상태 서버 (추가!)
          volumeMounts:
            - name: certs
              mountPath: /app
      volumes:
        - name: certs
          secret:
            secretName: ocr-certificates

---
apiVersion: v1
kind: Service
metadata:
  name: ocr-service
spec:
  type: ClusterIP
  selector:
    app: ocr
  ports:
    - name: qr
      port: 8080
      targetPort: 8080
    - name: proxy
      port: 3000
      targetPort: 3000
    - name: auth
      port: 3002     # 🔥 인증 상태 서버용 포트 추가
      targetPort: 3002
